"use strict";
var __cov_Ns0no$fj7eEd2x9KwBBlOA = (Function('return this'))();
if (!__cov_Ns0no$fj7eEd2x9KwBBlOA.__coverage__) { __cov_Ns0no$fj7eEd2x9KwBBlOA.__coverage__ = {}; }
__cov_Ns0no$fj7eEd2x9KwBBlOA = __cov_Ns0no$fj7eEd2x9KwBBlOA.__coverage__;
if (!(__cov_Ns0no$fj7eEd2x9KwBBlOA['/Users/jzhang/Documents/libraries/flow.js/src/dom/attributes/class-attr.js'])) {
   __cov_Ns0no$fj7eEd2x9KwBBlOA['/Users/jzhang/Documents/libraries/flow.js/src/dom/attributes/class-attr.js'] = {"path":"/Users/jzhang/Documents/libraries/flow.js/src/dom/attributes/class-attr.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0,"8":0,"9":0,"10":0,"11":0,"12":0,"13":0},"b":{"1":[0,0],"2":[0,0],"3":[0,0],"4":[0,0]},"f":{"1":0},"fnMap":{"1":{"name":"(anonymous_1)","line":9,"loc":{"start":{"line":9,"column":12},"end":{"line":9,"column":35}}}},"statementMap":{"1":{"start":{"line":3,"column":0},"end":{"line":30,"column":2}},"2":{"start":{"line":10,"column":8},"end":{"line":12,"column":9}},"3":{"start":{"line":11,"column":12},"end":{"line":11,"column":44}},"4":{"start":{"line":14,"column":8},"end":{"line":14,"column":54}},"5":{"start":{"line":15,"column":8},"end":{"line":17,"column":9}},"6":{"start":{"line":16,"column":12},"end":{"line":16,"column":30}},"7":{"start":{"line":18,"column":8},"end":{"line":20,"column":9}},"8":{"start":{"line":19,"column":12},"end":{"line":19,"column":49}},"9":{"start":{"line":22,"column":8},"end":{"line":24,"column":9}},"10":{"start":{"line":23,"column":12},"end":{"line":23,"column":37}},"11":{"start":{"line":25,"column":8},"end":{"line":25,"column":35}},"12":{"start":{"line":27,"column":8},"end":{"line":27,"column":29}},"13":{"start":{"line":28,"column":8},"end":{"line":28,"column":49}}},"branchMap":{"1":{"line":10,"type":"if","locations":[{"start":{"line":10,"column":8},"end":{"line":10,"column":8}},{"start":{"line":10,"column":8},"end":{"line":10,"column":8}}]},"2":{"line":15,"type":"if","locations":[{"start":{"line":15,"column":8},"end":{"line":15,"column":8}},{"start":{"line":15,"column":8},"end":{"line":15,"column":8}}]},"3":{"line":18,"type":"if","locations":[{"start":{"line":18,"column":8},"end":{"line":18,"column":8}},{"start":{"line":18,"column":8},"end":{"line":18,"column":8}}]},"4":{"line":22,"type":"if","locations":[{"start":{"line":22,"column":8},"end":{"line":22,"column":8}},{"start":{"line":22,"column":8},"end":{"line":22,"column":8}}]}}};
}
__cov_Ns0no$fj7eEd2x9KwBBlOA = __cov_Ns0no$fj7eEd2x9KwBBlOA['/Users/jzhang/Documents/libraries/flow.js/src/dom/attributes/class-attr.js'];
__cov_Ns0no$fj7eEd2x9KwBBlOA.s['1']++;module.exports={test:'class',target:'*',handle:function(value,prop){__cov_Ns0no$fj7eEd2x9KwBBlOA.f['1']++;__cov_Ns0no$fj7eEd2x9KwBBlOA.s['2']++;if(_.isArray(value)){__cov_Ns0no$fj7eEd2x9KwBBlOA.b['1'][0]++;__cov_Ns0no$fj7eEd2x9KwBBlOA.s['3']++;value=value[value.length-1];}else{__cov_Ns0no$fj7eEd2x9KwBBlOA.b['1'][1]++;}__cov_Ns0no$fj7eEd2x9KwBBlOA.s['4']++;var addedClasses=this.data('added-classes');__cov_Ns0no$fj7eEd2x9KwBBlOA.s['5']++;if(!addedClasses){__cov_Ns0no$fj7eEd2x9KwBBlOA.b['2'][0]++;__cov_Ns0no$fj7eEd2x9KwBBlOA.s['6']++;addedClasses={};}else{__cov_Ns0no$fj7eEd2x9KwBBlOA.b['2'][1]++;}__cov_Ns0no$fj7eEd2x9KwBBlOA.s['7']++;if(addedClasses[prop]){__cov_Ns0no$fj7eEd2x9KwBBlOA.b['3'][0]++;__cov_Ns0no$fj7eEd2x9KwBBlOA.s['8']++;this.removeClass(addedClasses[prop]);}else{__cov_Ns0no$fj7eEd2x9KwBBlOA.b['3'][1]++;}__cov_Ns0no$fj7eEd2x9KwBBlOA.s['9']++;if(_.isNumber(value)){__cov_Ns0no$fj7eEd2x9KwBBlOA.b['4'][0]++;__cov_Ns0no$fj7eEd2x9KwBBlOA.s['10']++;value='value-'+value;}else{__cov_Ns0no$fj7eEd2x9KwBBlOA.b['4'][1]++;}__cov_Ns0no$fj7eEd2x9KwBBlOA.s['11']++;addedClasses[prop]=value;__cov_Ns0no$fj7eEd2x9KwBBlOA.s['12']++;this.addClass(value);__cov_Ns0no$fj7eEd2x9KwBBlOA.s['13']++;this.data('added-classes',addedClasses);}};
